// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqxfmfCrzc1mygTL8PxyHSWNp3uIDTh8',
    appId: '1:59341988526:web:3f5249519b1898569cc33f',
    messagingSenderId: '59341988526',
    projectId: 'madrasati-d0c72',
    authDomain: 'madrasati-d0c72.firebaseapp.com',
    storageBucket: 'madrasati-d0c72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvevcjvARjFAal_tsjHWu8_FoHGGUftvc',
    appId: '1:59341988526:android:245ab9ca4f7e782a9cc33f',
    messagingSenderId: '59341988526',
    projectId: 'madrasati-d0c72',
    storageBucket: 'madrasati-d0c72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0cco5PM3kVgNxciR4j-fycwRVDuu4F8',
    appId: '1:59341988526:ios:e1538c779b3645879cc33f',
    messagingSenderId: '59341988526',
    projectId: 'madrasati-d0c72',
    storageBucket: 'madrasati-d0c72.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv0cco5PM3kVgNxciR4j-fycwRVDuu4F8',
    appId: '1:59341988526:ios:e1538c779b3645879cc33f',
    messagingSenderId: '59341988526',
    projectId: 'madrasati-d0c72',
    storageBucket: 'madrasati-d0c72.firebasestorage.app',
    iosBundleId: 'com.example.madrasatiApp',
  );

}